server:
  port: 8080
  servlet:
    context-path: /api
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sigabem
    username: ${DB_USER:root}
    password: ${DB_PASSWD:root}
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: create-drop
viacep.url: https://viacep.com.br/ws